RECORDING_DIR = "./recordings/"
FREQUENCY_SAMPLED = 8000
FRAME_MAX_LEN = 85
MFCC_FILTER_NUM = 20
MEL_FITER_NUM = 40


NUM_OF_DATA = 50
# TRAIN 80% VALID 10% TEST 10%
NUM_OF_TEST = NUM_OF_DATA * 0.1
NUM_OF_VALID = NUM_OF_DATA * 0.1

VALID_PERCENT = NUM_OF_VALID / (NUM_OF_DATA - NUM_OF_TEST)

NUM_OF_SPEAKERS = 6
NUM_OF_DIGITS = 10

